OT120-25 Endpoint actualizar usuario
alkemyTech/OT120-SERVER pull request #11
Opened 2021-12-20 21:59 UTC by MarisaCaponetto

![Screenshot []((67)](https://user-images.githubusercontent.com/73622295/146837738-39674797-18e3-492f-b385-9d87fe25159f.png))

https://alkemy-labs.atlassian.net/browse/OT120-25

2021-12-22 02:58 UTC, nicolascareri requested changes

2021-12-22 02:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +  private UserService userService;
el autowired va aca arriba, y se elimina el constructor

2021-12-22 02:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +  private List<User> users = new ArrayList<>();
No hace falta que le agregues la lista de users al role

2021-12-22 02:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +        for(User entity : userList){
Esto se deberia hacer con un stream map

2021-12-22 02:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +  public UserServiceImpl(IUserRepository userRepository, UserMapper userMapper){
Deberias poner el `@Autowired` arriba de la variable del mapper, y elimianr este constructor. Porque el repositorio ya tiene autowired

2021-12-22 02:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/dto/RoleDTO.java
> +    private List<UserDTO> users;
No hace falta que el role devuela la lista de usuarios que lo tienen asignado

2021-12-23 05:58 UTC, nicolascareri requested changes
Falta solamente resolver conflictos y tratar de cambiar el for each al map en el comentario que hice

2021-12-23 14:42 UTC, MarisaCaponetto commented
Evidencia:
![Screenshot (90)](https://user-images.githubusercontent.com/73622295/147255560-ca011cbb-95b6-439d-82a5-f357a546fd19.png)

2021-12-23 15:32 UTC, nicolascareri approved these changes

2021-12-23 15:32 UTC, merged