Endpoint Organizacion PUT
alkemyTech/OT120-SERVER pull request #16
Opened 2021-12-22 01:28 UTC by lumalnis

https://alkemy-labs.atlassian.net/browse/OT120-28?atlOrigin=eyJpIjoiZjQ3MGM1OTRlMmQzNGY1MzljMTI3ZGRiYzE4ODRlYWQiLCJwIjoiaiJ9

2021-12-22 02:50 UTC, nicolascareri requested changes

2021-12-22 02:50 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/dto/OrganizationAllDto.java
> +    @Positive
En este caso como indicas al `@Size` que sea minimo 8, el positive queda redundante. Habria que removerlo

2021-12-22 02:50 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            if (organization.getName().isEmpty()) {
Aca hay varias cosas para ver.  Por un lado estas preguntando si el get de la organization esta vacio, el problema es que preguntas por la organization que te traes de la base, osea la ya existente, en cambio deberias preguntar por el Name pero del dto que te viene, osea el nuevo name que queres poner. Y asi con el resto de los campos.

Por otro lado, todas estas validaciones las podrias agregar al DTO con `@NotBlank`, se lo deberias agregar a los campos que queres que sean mandatorios, y ya te anda porque tenes el `@Valid` en el requestBody en el controller.

2021-12-22 17:16 UTC, lumalnis commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            if (organization.getName().isEmpty()) {
Pero como hago si quiero saber si existe en la base de datos el objeto  que quiero actualizar?

2021-12-22 18:00 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            if (organization.getName().isEmpty()) {
ya lo estas haciendo con el optional.isPresent()

2021-12-22 18:03 UTC, lumalnis commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            if (organization.getName().isEmpty()) {
Ahh listo me habia mareado. Entonces cambio a todos los organization x dto y estaria

2021-12-22 18:04 UTC, lumalnis commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            if (organization.getName().isEmpty()) {
en realidad, elimino esos if y lo valido en el dto

2021-12-23 05:55 UTC, nicolascareri reviewed
Habria que revisar el comentario mio y resolver los conflictos

2021-12-23 05:55 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            organizationRepository.save(organization);
creo que te falta setearle el ID antes de persistirlo

2021-12-23 16:06 UTC, nicolascareri requested changes

2021-12-23 16:06 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +            Organization organization = optional.get();
esta linea esta de mas

2021-12-24 19:40 UTC, lumalnis commented
![image](https://user-images.githubusercontent.com/83096790/147370442-74f29f11-20dc-4b93-8e4d-2c7771d2ec2d.png)

Turco lo que me quedó duda es que en la entidad me hico agregarle:
public void setId(Long id) {
    this.id = id; 
  } o no me dejaba setear el ID en el update. Esta bien?

2021-12-27 00:34 UTC, turcoamado requested changes
Te dejé un comentario que creo que responde lo que me consultabas con respecto al id

2021-12-27 00:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/OrganizationAllDto.java
> +    //@Size(min = 8, max = 11)
Este por qué está comentado? Si no lo vamos a utilizar mejor borrarlo

2021-12-27 00:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/entity/Organization.java
> +    this.id = id; //Sin esto no me deja setear el ID en el UPDATE
Realmente no se si hay que realizar esto, no deberíamos. Porque el ID es una referencia única para la DB, si queremos realizar una actualización se realiza sobre ese registro, no debemos por qué modificar el ID, así que yo directamente se lo sacaría

2021-12-27 18:42 UTC, lumalnis commented on src/main/java/com/alkemy/ong/model/entity/Organization.java
> +    this.id = id; //Sin esto no me deja setear el ID en el UPDATE
**Acá paso de dto a entidad para guardarlo y el dto no me trae el ID y si no le seteo el ID que ya tenía me genera uno nuevo.**

public OrganizationAllDto update(OrganizationAllDto dto, Long id) throws Exception {
        Optional<Organization> optional = organizationRepository.findById(id);
        if (optional.isPresent()) {
            Organization organization = organizationMapper.organizationDto2EntityAll(dto);
            organization.setId(id);
            organizationRepository.save(organization);
        } else {
            throw new EntityNotFoundException(ORGANIZATION_NOT_FOUND_MESSAGE);
        }
        return dto;
    }
}

2021-12-27 18:42 UTC, lumalnis commented on src/main/java/com/alkemy/ong/dto/OrganizationAllDto.java
> +    //@Size(min = 8, max = 11)
Hola Turco! Perdón eso se supone que va pero en el postman me tiraba error al colocar un numero, será por el Integer? Porque en el caso de los String no lo hace.

2021-12-30 00:43 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/entity/Organization.java
> +    this.id = id; //Sin esto no me deja setear el ID en el UPDATE
Los DTO los utilizamos para enviar datos de una capa a otra, son objetos que creamos para no alterar justamente la integridad de los datos. El error está en pedir en el service el id para actualizarlo, el id lo usamos únicamente para buscar un objeto en este caso, si tengo que realizar un update actualizo todos los campos menos el id, el id es el mismo siempre, es lo que me referencia a ese objeto en la base de datos, no puedo modificarlo. Fijate que en la creación del objeto no lo seteas, la estrategia de creación le asigna uno.
Si crearon los endpoints de creación diciendo que se tienen que setear el id entonces estaría mal, pero bueno no se si vale la pena modificar todo porque no vamos a avanzar más, pero en rigor no deberían actualizar los id nunca.

2021-12-30 00:44 UTC, turcoamado requested changes
te hice un comentario con respcto al id, avisame si lo ves, si tenes dudas o cualquier cosa. Para que puedas entender y vemos si no es algo que se realizó de esta forma en todo lo demás, pero conceptualmente está mal actualizar un ID.

2022-01-05 04:02 UTC, merged