endpoint list category for only name
alkemyTech/OT120-SERVER pull request #2
Opened 2021-12-17 15:38 UTC by EnzoL1016

**Summary**

create the category dto with its mapping and its controller

**Evidence**

![Prueba-Dto-Category](https://user-images.githubusercontent.com/92378273/146568605-5cb02e92-150f-4133-8544-f5b3242d490b.png)

2021-12-17 15:46 UTC, nicolascareri requested changes
Acordate de ponerme el numero del ticket en el nombre del PR tambien. No veo que en la evidencia traiga algun dato. Revisalo

2021-12-17 15:46 UTC, nicolascareri commented on nbactions.xml
> +            <properties>
Que es este archivo?

Revisar

2021-12-17 15:46 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/entity/dto/CategoryDtoMapping.java
> +            List<Category> entities = categoryRepository.findAll();
Estas mesclando logica del servicio con la del DTO. Esto no esta bien. 

El mapping solo deberia hacer la parte del map valga la redundancia. Pero el manejo a los repositorios y demas logica la dfeberia ahcer el servicio

2021-12-17 15:46 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        categoryDto.findAll();
Aca deberias llamar al servicio

2021-12-17 15:46 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    public ResponseEntity<?> findAll() throws Exception{
Dentro del <> del response Entity deberiamos indicar el tipo que estamos retornando en vez del "?" para darle mas legibilidad al codigo

2021-12-17 15:50 UTC, EnzoL1016 commented on nbactions.xml
> +            <properties>
Tengo jdk 15 y eso es un archivo que se crea por defecto

2021-12-17 20:20 UTC, nicolascareri commented on nbactions.xml
> +            <properties>
Okas, entonces no lo deberiamos commitear porque no suma nada

2021-12-17 22:21 UTC, nicolascareri requested changes

2021-12-17 22:21 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/entity/dto/CategoryDtoMapping.java
> +@Service
Esto no es un servicio, no esta bien.

Si lo estas usando para poder hacerle autowired en otro lado deberias usar `@Component`

2021-12-17 22:21 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/entity/dto/CategoryDtoMapping.java
> +            for(Category category : entities){
esto estaria mucho mas clean con un map de stream con lambda

2021-12-20 14:53 UTC, nicolascareri requested changes

2021-12-20 14:53 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(categoryService.findAlldto());
No esta bueno que llames al CategoryDtoService porque estas haciendo un paso extra sin sentido. Fijate que si podes llamar al categoryService findAll directamente. Esto seria lo correcto

2021-12-20 14:53 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/response/CategoryDtoMapping.java
> +    public List<CategoryDto> findAll()throws Exception{
No le veo mucho sentido a esto, desde el controllador se deberia llamar derecho a categoryService.findAll();

2021-12-20 19:20 UTC, nicolascareri approved these changes

2021-12-20 19:20 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import com.alkemy.ong.model.response.CategoryDtoMapping;
esto para que seria?

2021-12-20 19:20 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(categoryService.findAll());
Aca deberias llamar al findAll del CategoryServiceImpl, y ahi internamente traer los registros y hacer el mapeo. No esta bien que desde el controlador se llame al mapper y que eso adentro llame al servicio

2021-12-20 19:20 UTC, merged