Ot120 34 endpoint actualizacion categorias
alkemyTech/OT120-SERVER pull request #20
Opened 2021-12-23 13:44 UTC by Melwil1989

![DB antes del put](https://user-images.githubusercontent.com/79877606/147248899-f3387c8b-e860-443f-9607-5fcc432989e2.png)
![Postman Put categories](https://user-images.githubusercontent.com/79877606/147248919-7b9959af-a871-43a8-82c1-12f7313cf31c.png)
![DB despues del put](https://user-images.githubusercontent.com/79877606/147248928-7d41f802-307c-4546-9cee-057cf2496ab9.png)

2021-12-23 15:47 UTC, nicolascareri requested changes
Esta todo OK, falta remover el archivo NewsResponseDto del PR porque no se usa y resolver conflictos

2021-12-23 15:47 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/response/NewsResponseDto.java
> +public class NewsResponseDto {
Para que incluis este archivo en el PR si no lo usas?

2021-12-24 17:34 UTC, turcoamado requested changes
Te falta resolver los conflictos en **ICategoryService.java**

2021-12-30 00:45 UTC, turcoamado approved these changes

2021-12-30 00:48 UTC, turcoamado requested changes
Che, me aparecen conflictos con el nombre de SecurityConfig, por qué razón lo renombraste y lo metiste en el package mapper? eso tenes que dejarlo como estaba, en config

2021-12-30 15:45 UTC, turcoamado approved these changes

2021-12-30 15:46 UTC, merged