Agregado atributos url de Facebook, Linkedin e Instagram OT120-9
alkemyTech/OT120-SERVER pull request #23
Opened 2021-12-25 23:12 UTC by Abel3581

Agregados

- Atributo y interacción con bases de datos, de facebook, linkedin, instagram.
<img width="797" alt="4" src="https://user-images.githubusercontent.com/59884602/147394877-0adf0226-58fd-4d23-a613-b6cd58717308.png">

Link jira: 

https://alkemy-labs.atlassian.net/browse/OT120-52

2021-12-27 01:14 UTC, turcoamado requested changes
Te falta modificar el servicio según los criterios de aceptación:

> Criterios de aceptación:
Modificar modelo, repositorio y servicio para agregar las urls de redes sociales a una Organización. Se deberán agregar url de Facebook, Linkedin e Instagram

2021-12-27 03:36 UTC, Abel3581 commented
Tengo que hacer un  post de organization con su service y repository , no entiendo el enunciado ?

2021-12-27 03:49 UTC, turcoamado commented
> Tengo que hacer un post de organization con su service y repository , no entiendo el enunciado ?

Sería modificar el service para que el endpoint de listar pueda mostrar las redes sociales agregadas, porque seguramente así como está ahora si haces el get no te va a traer los datos que acabas de agregar en este PR

2021-12-27 20:50 UTC, Abel3581 commented
Acabo de actualizar.

2021-12-30 01:37 UTC, turcoamado requested changes
Tenes conflictos en estos archivos
src/main/java/com/alkemy/ong/config/security/SecurityConfig.java
src/main/java/com/alkemy/ong/controller/UserController.java

Y no entiendo bien por qué estás agregando SlideDtoGet, lo haces para que ademas te traiga el listado entiendo, no? No está mal, pero no corresponde a otra tarea?

Lo más importrante es resolver los conflictos ahora

2021-12-30 21:26 UTC, Abel3581 commented
Corrección de errores y eliminación de trabajo que no era mío.

2021-12-31 21:43 UTC, turcoamado approved these changes
Barbaro!

2021-12-31 21:43 UTC, merged