Ot120 37 endpoint actualizacion novedades
alkemyTech/OT120-SERVER pull request #26
Opened 2021-12-27 19:41 UTC by lumalnis

Hola Turco, te dejo el pr de este Update, lo hice de otra forma (a lo que habia hecho en el update de organizacion) y funciona bien según el postman. Si te parece que esta bien hago el de organizacion de la misma manera. 
![image](https://user-images.githubusercontent.com/83096790/147502433-8cb034ab-91ad-4a36-8c9b-b633daf5a089.png)

2021-12-30 02:18 UTC, turcoamado requested changes
Claaaaro! Ahora si! Bien ahí! Este está bárbaro, pero no lo puedo aprobar porque estan el update de Organization..
Si queres modificalo sobre esto mismo ya que estamos y cerramos ambas, pero es con esta idea, hiciste bien lo de news!

2021-12-31 22:05 UTC, turcoamado reviewed
Me figura que tenes conflictos en estos archivos

2021-12-31 22:05 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
> +        if (organizationOptional.isEmpty() || organizationOptional.get().isSoftDelete()) {
Mira, aca es lo mismo que hiciste con organization, sacarle la validacion del softDelete

2021-12-31 22:05 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/entity/Organization.java
> +  public void setId(Long id) {
Este metodo ahora si lo podemos boletear no?

2021-12-31 22:06 UTC, turcoamado requested changes
Me figura que tenes confglictos en estos archivos 
src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
src/main/java/com/alkemy/ong/model/entity/Organization.java
src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java

2022-01-04 19:19 UTC, lumalnis commented
![image](https://user-images.githubusercontent.com/83096790/148111903-638b69fa-64df-4151-b27a-e13a408fd906.png)
---------------------
Ya solucione esto. O por lo menos no me saltan ahora.
-----------------------
Me figura que tenes confglictos en estos archivos
src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
src/main/java/com/alkemy/ong/model/entity/Organization.java
src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java

2022-01-05 04:11 UTC, closed without merging

2022-01-05 04:11 UTC, turcoamado commented
Already merged in other one