Ot 120 44 endpoint almacenar contactos
alkemyTech/OT120-SERVER pull request #27
Opened 2021-12-28 14:52 UTC by Cortinezjuan

Summary:
I create the endpoint to store contacts in the database; I create ContactDto, ContactMapper, ContacController class, add methods in ContactService class and add methods for error handling.
Evidence:

![Base de datos](https://user-images.githubusercontent.com/64449356/147578333-4d87a891-9263-4302-af87-a4dc4f550322.JPG)
![email empty](https://user-images.githubusercontent.com/64449356/147578334-7e04e353-0cda-4679-945d-2a7cede4ffd0.JPG)
![name empty](https://user-images.githubusercontent.com/64449356/147578335-c02a3fea-4999-4497-8e44-ed128de9691d.JPG)
![name,email empty](https://user-images.githubusercontent.com/64449356/147578336-530bdeb6-d524-4279-a14c-f196a9d801b3.JPG)
![Postman](https://user-images.githubusercontent.com/64449356/147578337-05de560e-dc08-48d4-a845-5fe448f8c97f.JPG)

link to task OT-120-44
https://alkemy-labs.atlassian.net/browse/OT120-44?atlOrigin=eyJpIjoiMmViODVlZTNmMThkNDNiOGE5ODc0ZDM1M2E5OGQ0YTMiLCJwIjoiaiJ9

2021-12-30 02:50 UTC, turcoamado requested changes
El PR está bastante bien, me gusta que hayas codedao una exception particular, es una buena práctica, pero le pifiaste con el nombre y el HttpStatus (no pasa nada, no es grave)
Chequeate los comentarios que te fui realizando y los conflictos, pero la base está bien

2021-12-30 02:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ContactController.java
> +    public ResponseEntity<ContactDto> save(@Valid @RequestBody ContactDto contactDto, BindingResult error){
No está mal, pero me parece que acá el BindingResult y el tratamiento de si hasFieldErrors() es redundante, porque lo estaríamos manejando con la annotation @Valid. Probaste qué pasa si no lo usas? Fijate y comentame

2021-12-30 02:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/ContactServiceImpl.java
> +    public ContactDto save(ContactDto contactDto) {
Bueno este método está casi perfecto. Casi porque en realidad no es un NullPointerException lo que está pasando, esa exception es propia del lenguaje y lo que quiere decir es que no se encontró algo que se fue a buscar, acá lo que viene en null es algo del dto, se podría manejar de otra manera, y como es una exception que vos estás escribiendo debería tener otro nombre

2021-12-30 02:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/ExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
Esto debería ser un HttpStatus.BAD_REQUEST, porque el INTERNAL_SERVER_ERROR denota un error que arroja el server pero donde el user hizo todo lo que debía hacer de forma correcta, en cambio acá se está arrojando cuando falta enviar algún dato, por lo que en realidad correspondería un BAD_REQUEST, el error es del user no del server. Se entiende la diferencia?
Podés chusmear acá mira: https://enterprisecraftsmanship.com/posts/rest-api-response-codes-400-vs-500/

2021-12-30 14:06 UTC, Cortinezjuan commented on src/main/java/com/alkemy/ong/controller/ContactController.java
> +    public ResponseEntity<ContactDto> save(@Valid @RequestBody ContactDto contactDto, BindingResult error){
Buenos días Turco, si lo estuve probando, si no lo uso, valida que algun campo está vacío pero  me devuelve toda la traza del error

2021-12-30 15:49 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ContactController.java
> +    public ResponseEntity<ContactDto> save(@Valid @RequestBody ContactDto contactDto, BindingResult error){
Bueno dejalo entonces, no hay drama

2021-12-31 22:39 UTC, turcoamado requested changes
Falta resolver los conflictos y estamos

2022-01-05 02:31 UTC, turcoamado approved these changes

2022-01-05 02:31 UTC, merged