Ot120 16 endpoint registro de usuarios
alkemyTech/OT120-SERVER pull request #3
Opened 2021-12-17 21:32 UTC by flordife

Se crea en endpoint postUser ("/auth/register") en el controller. Se crea en el UserService el método postUser con las verificaciones de nombre, email y apellido. Se encripta la password. Se prueba con Postman el endpoint. Se adjunta imagen de prueba.
![OT-120](https://user-images.githubusercontent.com/75486164/146610420-863cf6e6-0ac8-49c8-bb5f-36d18e5e9410.png)

2021-12-17 21:34 UTC, flordife commented
Se agregan también los models correspondientes y las Exceptions a cada validación

2021-12-17 22:18 UTC, nicolascareri requested changes

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    r.username =user.getUsername();
aca deberias usar un setter. r.setUsername(user.getUsername());

Al setearselo derecho estas violando una de las principales reglas de la programacion orientada a objetos uqe es la encapsulacion.

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return ResponseEntity.ok(r);
Aca suele ser mas legible devolver algo asi.

return new ResponseEntity<>( r , HttpStatus.OK );

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    User user = userService.postUser(req.firstName, req.lastName, req.email, req.password);
aca es preferible mandarle el req entero como parametor en vez de cada uno de los campos

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/exception/FirstNameInvalidException.java
> +public class FirstNameInvalidException extends RuntimeException {
Unificar todas las excepciones en una, o usar el @NotBlank en los DTO

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/exception/FirstNameInvalidException.java
> +@ResponseStatus(HttpStatus.FORBIDDEN)
Esto deberia ser badrequest

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/request/RegistrationRequest.java
> +public class RegistrationRequest {
A esto le falta los getter y los setter

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/response/RegistrationResponse.java
> +@Getter
le falta el setter

2021-12-17 22:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +  private boolean emailExists(final String email) {
no hace falta el "final"

2021-12-17 22:19 UTC, nicolascareri commented
Estaria bueno que el DTO del response devuelva mas datos del usuario, te diria uqe practicamente todos menos la password

2021-12-17 22:26 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    User user = userService.postUser(req.firstName, req.lastName, req.email, req.password);
le suma legibilidad

2021-12-18 15:54 UTC, flordife commented
Se agregan los cambios pedidos. Se agregan anotaciones en los models. Se refactoriza los métodos postUser del Controller y del Service. Se añaden más datos al Response de Usuario. Se adjunta screen de Postman
![Sin título](https://user-images.githubusercontent.com/75486164/146647256-45dbb781-7405-47e4-ad7f-b835bac888eb.png)

2021-12-20 19:35 UTC, nicolascareri requested changes

2021-12-20 19:35 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/request/RegistrationRequest.java
> +    @NotEmpty (message = "La contraseña no puede estar vacía")
Con el `@NotBlank` ya alcanzaria en cada uno de los campos, ya verifica internamente que no sea null tambien

2021-12-20 19:51 UTC, flordife commented on src/main/java/com/alkemy/ong/model/request/RegistrationRequest.java
> +    @NotEmpty (message = "La contraseña no puede estar vacía")
![image](https://user-images.githubusercontent.com/75486164/146824443-64f97e17-aee8-48d0-96a0-a4b75b8151d7.png)

2021-12-20 20:04 UTC, nicolascareri approved these changes

2021-12-20 20:04 UTC, merged