OT120-48 creo el metodo update en SlideServiceImpl para poder actuali…
alkemyTech/OT120-SERVER pull request #30
Opened 2021-12-29 21:08 UTC by Melwil1989

…zar los datos de un slide, junto con el endpoint en el controller. Tambien agrego el permiso para usuario administrador en el securityConfig, para que solo un usuario autorizado pueda acceder al metodo.

2021-12-29 21:11 UTC, Melwil1989 commented
Captura de la DB antes de ejecutar el put
![DB antes del put2](https://user-images.githubusercontent.com/79877606/147703558-dc84603a-2e37-43f5-94cc-5cf65ab647c4.png)

Captura del postman al ejecutar el put
![Postman Put slides](https://user-images.githubusercontent.com/79877606/147703602-b7a38dc2-f061-424c-ba67-e997441b57bf.png)

Captura de la DB despues de ejecutar el put
![DB despues del put2](https://user-images.githubusercontent.com/79877606/147703630-2213c37d-2e1c-4ab7-aff0-02189198c24c.png)

Si paso un id que no existe
![Si el id no existe](https://user-images.githubusercontent.com/79877606/147703650-110acd75-77fe-40dd-a0f1-cc6f0587a85f.png)

2021-12-30 03:22 UTC, turcoamado requested changes
Además del comentario que te realicé tenes unos conflictos

2021-12-30 03:22 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +      Organization organization = new Organization();
Esta parte no está bien, porque lo que necesitamos es actualizar el slide correspondiente a una organización (en este caso la única que tenemos), si creamos un objeto Organization, que hacemos con eso? Como se comportaría la aplicación? Si estamos haciendo todo para la misma organization..se entiende? 
No deberíamos tocar nada de la organization acá, porque la slide ya corresponde a una, entonces esa realción no cambiaría en absoluto, te pongo un ejemplo:
Suponete que queres cambiar las cubiertas del auto, vas a una gomería, compras las cubiertas y las pones, pero no tenes por qué comprar un auto también y meterle esas cubiertas a otro auto. Fue lo primero que se me ocurrió pero creo que va a servirte para esclarecer un poco.

2022-01-02 22:09 UTC, Melwil1989 commented
![DB antes del put](https://user-images.githubusercontent.com/79877606/147890664-0626d3f0-267f-4f0f-9624-9ad7b73d4352.png)
![Respuesta postman put](https://user-images.githubusercontent.com/79877606/147890666-7ff2bb24-2383-4678-b9b9-dec86647fc81.png)
![DB despues del put](https://user-images.githubusercontent.com/79877606/147890670-b8a8dd1f-3f77-4542-a46b-d3920ac3487e.png)

2022-01-02 22:19 UTC, turcoamado approved these changes

2022-01-02 22:19 UTC, merged