Ot120 41 endpoint update activities
alkemyTech/OT120-SERVER pull request #31
Opened 2021-12-31 18:49 UTC by facupaez

- Crear PUT /activities/{id}
- Validar que el id enviado por parametro exista en la bd, caso contrario devolver error
- Actualizar actividad y devolver actualizacion

![pr update activity2](https://user-images.githubusercontent.com/54560646/147836042-1a8c151f-5d88-4fab-aafa-ac0f7457f045.png)
![pr update activity](https://user-images.githubusercontent.com/54560646/147836045-fd579d02-bd49-4609-8182-20f4be82206f.png)

2021-12-31 22:49 UTC, turcoamado requested changes
Fijate el comentario y de resolver los conflictos

2021-12-31 22:49 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/ActivityServiceImpl.java
> +            throw new ParamNotFound("El id ingresado no existe.");
Esta exception esta devolviendo mal el codigo http, no puede ser un 500 (HttpStatus.BAD_REQUEST), eso es un error que arroja el server pero donde el user hizo todo lo que debía hacer de forma correcta, en cambio acá se está arrojando cuando falta enviar algún dato, por lo que en realidad correspondería un BAD_REQUEST, el error es del user no del server. Se entiende la diferencia?
Se lo habia comentado a uno de tus compas.
Podés chusmear acá mira: https://enterprisecraftsmanship.com/posts/rest-api-response-codes-400-vs-500/

2022-01-01 14:37 UTC, facupaez commented
![pr update activity3](https://user-images.githubusercontent.com/54560646/147852962-e791e63f-5e1a-43c0-8f4f-e235ddaffa7a.png)

Por el tema de conflictos no veo ninguno por el momento..

2022-01-02 20:11 UTC, turcoamado approved these changes

2022-01-02 20:11 UTC, merged