Seeder of Activities created
alkemyTech/OT120-SERVER pull request #33
Opened 2022-01-02 23:20 UTC by mtsdlf

https://alkemy-labs.atlassian.net/browse/OT120-42?atlOrigin=eyJpIjoiNDNkNzA5ZWEzZjMwNGExNzhiYjQ3MTQyYTBjM2E1ODAiLCJwIjoiaiJ9
![evidencia 2](https://user-images.githubusercontent.com/28317445/147892056-08df57ac-a9ae-4c9a-a5aa-2cb8245c4c9f.png)

2022-01-03 00:45 UTC, turcoamado requested changes

2022-01-03 00:45 UTC, turcoamado commented on src/main/java/com/alkemy/ong/seeder/ActivitySeeder.java
> +			Activity activity1 = new Activity(1, "Utiles escolares para escuelas municipales", "Utiles escolares para escuelas municipales (...)", "image.org/image_1.png", null, false);
El primer parametro es el id? Porque si corresponde al id (y creo que si lo hace) tenemos un problema, se estan creando dos con el mismo id. Sin embargo, si no te fallo la creacion es porque esta creando los id por su cuenta (como deberia ser), por lo que no seria necesario pasarle el id.
Conclusion, proba de nuevo sin enviarle ese parametro y en caso de ser obligatorio entonces ponele otro id diferente.

2022-01-03 00:45 UTC, turcoamado commented on src/main/java/com/alkemy/ong/seeder/ActivitySeeder.java
> +	IActivityRepository activityRepository;
Agregale private a esta variable

2022-01-04 19:23 UTC, mtsdlf commented on src/main/java/com/alkemy/ong/seeder/ActivitySeeder.java
> +			Activity activity1 = new Activity(1, "Utiles escolares para escuelas municipales", "Utiles escolares para escuelas municipales (...)", "image.org/image_1.png", null, false);
Si es el ID, es un parámetro obligatorio.

2022-01-04 19:23 UTC, mtsdlf commented
PR updated

2022-01-05 03:23 UTC, turcoamado approved these changes

2022-01-05 03:23 UTC, merged