Ot120 55 endpoint actualizacion testimonios
alkemyTech/OT120-SERVER pull request #34
Opened 2022-01-03 00:26 UTC by mtsdlf

https://alkemy-labs.atlassian.net/browse/OT120-55?atlOrigin=eyJpIjoiOTU4N2QyN2NiZDc3NGJhZDhhOTQyMDdmODU3MzkxNWEiLCJwIjoiaiJ9
![evidencia](https://user-images.githubusercontent.com/28317445/147893193-5c4b3839-1d60-488e-af39-5b67c4c9791d.png)

2022-01-03 00:50 UTC, turcoamado requested changes

2022-01-03 00:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +	return new ResponseEntity<TestimonialRequestDto>(dto, HttpStatus.CREATED);
Como es un update le cambiaria el CREATED por un OK

2022-01-04 19:21 UTC, mtsdlf commented
PR updated

2022-01-05 03:27 UTC, turcoamado approved these changes

2022-01-05 03:27 UTC, merged