Ot120 21 integrar template email bienvenida
alkemyTech/OT120-SERVER pull request #35
Opened 2022-01-03 13:49 UTC by MarisaCaponetto

Se integra plantillaHTML a mail de bienvenida que se envia cuando el usuario se registra en el sitio web. Para ello se creó el metodo preparedWelcomeBodyEmail en EmailServiceImpl donde se setearon las variables que son utilizadas en la plantilla html. Se modificó el metodo Save de UserServiceImpl en su linea 119, donde se insertó el metodo sendWelcomeEmail, que fue creado en EmailServiceImpl para la utilizacion de la plantilla en el envio de mail. Se envia evidencia, de Postman, de log, mail recibido, y de base de datos donde se ha creado exitosamente el usuario.

![Screenshot (173)](https://user-images.githubusercontent.com/73622295/147937631-2a9c24ac-1c51-45ba-9d14-03c38a61c698.png)
![Screenshot (172)](https://user-images.githubusercontent.com/73622295/147937809-54e3dfef-f5fc-4be2-a431-672e4f4647e9.png)
![Screenshot (169)](https://user-images.githubusercontent.com/73622295/147937879-15c56a24-3389-4947-8ec7-7227ddd78493.png)
![image](https://user-images.githubusercontent.com/73622295/147937928-3166dc05-93ca-4292-a4c3-540d33603cff.png)

2022-01-04 06:05 UTC, turcoamado requested changes
Me figura que tenes conflictos en algunos archivos.

Por otro lado, el logo y la imagen al final como quedaron? Te consulto porque veo dos lineas comentadas con repspecto a eso, una en EmailServiceImpl y la otra en MailMessage (un enum)

2022-01-04 11:53 UTC, MarisaCaponetto commented
Buenos dias Turco! Las deje comentadas porque debo esperar a Mauro y quien a su vez debe esperar a Enzo, para terminar los tickets relacionados a Amazon. Por lo cual, las dejé comentadas como sugeriste por Discord hasta que ambos tickets (de Mauro y Enzo) estén implementados y funcionando. Así como lo dejé con las líneas comentadas, funciona el envio de mail con la plantilla HTML, sin la imagen por el momento. Saludos!

2022-01-05 15:23 UTC, MarisaCaponetto commented
Hola Turco! Ya realicé la resolucion de conflictos y agregue la imagen en el mail de bienvenida! Adjunto captura de imagen que está funcionando, saludos!
![Screenshot (210)](https://user-images.githubusercontent.com/73622295/148241559-9b05abf0-7306-484b-b9b2-b31526937fad.png)
!
![imagen](https://user-images.githubusercontent.com/73622295/148242763-7e7e22a1-579e-4256-824e-ed1ef3680355.png)

2022-01-05 16:01 UTC, turcoamado approved these changes

2022-01-05 16:10 UTC, merged