Ot 120 46 detalle slides
alkemyTech/OT120-SERVER pull request #37
Opened 2022-01-03 16:43 UTC by Cortinezjuan

Summary:
I create the methods in the controller and service class to show the details of a slides by Id

Evidence:

Link OT120-46: https://alkemy-labs.atlassian.net/browse/OT120-46?atlOrigin=eyJpIjoiYTRkZjIxODc4ODA3NGFlN2FjZjVmYzEyN2RmZjM4ZDQiLCJwIjoiaiJ9
![BdSlides](https://user-images.githubusercontent.com/64449356/147956333-0f06087f-0874-4a8c-a874-55a8da9938ad.JPG)
![SlidesById](https://user-images.githubusercontent.com/64449356/147956336-ac8c3b76-e759-4493-a961-c458ac30883b.JPG)

2022-01-04 06:15 UTC, turcoamado requested changes
Me figura que tenes dos conflictos

2022-01-04 06:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    return ResponseEntity.status(HttpStatus.OK).body(SlideService.getById(id));
el nombre de la variable slideService esta con mayuscula? Debe iniciar con minuscula

2022-01-04 11:25 UTC, Cortinezjuan commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    return ResponseEntity.status(HttpStatus.OK).body(SlideService.getById(id));
Si perdón, usé una variable que ya estaba definida y lo pasé por alto, ahora lo modifico

2022-01-05 03:17 UTC, turcoamado approved these changes
Listo! Lo dejo aprobado, me figura un conflicto, si lo resolves mergealo nomas!

2022-01-05 03:21 UTC, turcoamado approved these changes
Al final te lo resolví yo!

2022-01-05 03:22 UTC, merged