added members pagination
alkemyTech/OT120-SERVER pull request #47
Opened 2022-01-09 06:15 UTC by facupaez

Agregar paginacion a la clase Member, paginar de a 10 registros, filtro "page" para ir a la pagina que se requiera.

Correccion ORGANIZATIONS_ID en clase Slide.
![pr paginar miembros](https://user-images.githubusercontent.com/54560646/148671462-1f334a9f-685e-463c-9cb0-dee4cf3dfdf9.PNG)

2022-01-10 21:25 UTC, turcoamado requested changes
Consulta, la pag siguiente y anterior la estas mostrando? Se debe mostrar un link hacia la anterior y la siguiente. Y otra cosa, la pag 0 se la pasas siempre por parametro? porque veo que en el endpoint tenes siempre el 0 seteado

2022-01-10 21:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +    public ResponseEntity<Page<MemberDto>> getAllMembersPaged(@PageableDefault(size = 10, page = 0) Pageable pageable) {
el page = 0 no debería ser seteado con lo que le envias en el request?

2022-01-10 21:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +        //return new ResponseEntity(membersService.getAllMember(),HttpStatus.OK);
Esto eliminalo si no lo estas usando

2022-01-10 21:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/IMemberRepository.java
> +    //Page<Member> findBy(Pageable pageable);
Como estas resolviendo que se tome la pag deseada?

2022-01-10 22:45 UTC, facupaez commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +    public ResponseEntity<Page<MemberDto>> getAllMembersPaged(@PageableDefault(size = 10, page = 0) Pageable pageable) {
Seteo en 0 el page para que al inicio aparezca en la pagina "0". Despues por parametro se puede mover a la pagina que se quiera

2022-01-10 22:48 UTC, facupaez commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +        //return new ResponseEntity(membersService.getAllMember(),HttpStatus.OK);
Si este comentario me quedo colgado

2022-01-10 22:52 UTC, facupaez commented on src/main/java/com/alkemy/ong/repository/IMemberRepository.java
> +    //Page<Member> findBy(Pageable pageable);
JpaRepository extiende de PagingAndSortingReposityory, utilizo el findAll de esta clase en el ServiceImpl

![image](https://user-images.githubusercontent.com/54560646/148851413-bf3e0f8d-f6c1-4186-92a3-fa1ceb0c9f88.png)

2022-01-10 22:56 UTC, facupaez commented on src/main/java/com/alkemy/ong/repository/IMemberRepository.java
> +    //Page<Member> findBy(Pageable pageable);
Deberia elimnar esa linea comentada tambien

2022-01-11 20:35 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/IMemberRepository.java
> +    //Page<Member> findBy(Pageable pageable);
buenisimo!

2022-01-14 20:28 UTC, facupaez commented
Listo Nico ahi modifique el paginado con la dependencia hateoas como lo tiene Lu, ahi quedo por lo menos fijate si va asi
![pr paginar miembros](https://user-images.githubusercontent.com/54560646/149580838-ef137c61-d6f0-478f-a528-43e94ee711a7.PNG)

2022-01-14 20:41 UTC, nicolascareri approved these changes

2022-01-14 20:45 UTC, nicolascareri approved these changes

2022-01-14 21:16 UTC, merged