Ot120 63 endpoint actualizacion comentarios
alkemyTech/OT120-SERVER pull request #48
Opened 2022-01-09 23:08 UTC by mtsdlf

https://alkemy-labs.atlassian.net/browse/OT120-63?atlOrigin=eyJpIjoiZTdjZDE4YmRhYWQyNGU3YzkxYzdmNmM2OGY5OWQ3OTUiLCJwIjoiaiJ9

Evidence Update Comment As User
![updateComment_200_AsUser](https://user-images.githubusercontent.com/28317445/148704900-bc4c0f0b-b6fb-46d6-b902-d4149b76714c.png)

Evidence Update Comment As User Not Authorized
![updateComment_403_AsUser](https://user-images.githubusercontent.com/28317445/148704901-c557addc-eaa1-41d0-9861-1d8d1ad6c5fd.png)

Evidence Update Comment As Admin
![updateComment_200_AsAdmin](https://user-images.githubusercontent.com/28317445/148704903-74706afe-2ac9-4e92-9c1b-624b9d5e5d96.png)

Evidence Update Comment But Comment Not Found
![updateComments_404](https://user-images.githubusercontent.com/28317445/148704904-34a36b73-34f0-469a-8e4a-df990e03b3fd.png)

2022-01-10 21:29 UTC, turcoamado requested changes
En el security config me aparece como que estas eliminando un monton de lineas, chequeate eso porfa y confirmame si está OK. Entiendo que acabas de cambiar la forma en la que chequeas los permisos, pero testeaste que todo esté funcionando?

2022-01-10 21:29 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CommentController.java
> +    CommentsService.update(id, dto, authorizationHeader);
No me di cuenta antes, pero esta variable debe estar con minúscula, es una cuestión de buenas prácticas nada más.

2022-01-17 00:32 UTC, mtsdlf commented
PR updated

2022-01-17 14:23 UTC, nicolascareri approved these changes

2022-01-17 14:23 UTC, merged