se agrega el endpoint get para listar los comentarios por id de news,…
alkemyTech/OT120-SERVER pull request #49
Opened 2022-01-10 00:47 UTC by flordife

… se agrega el permiso para que cualquier usuario pueda verlo, se agrega el metodo findAll() en el service de comentario para poder realizar el getCommentsByNewsId() del NewsService

2022-01-10 22:15 UTC, turcoamado requested changes
Tenes dos conflictos, te dejé un comentario de nombre de variable y algo en un for (que ese no es necesario modificar, sino que es otra manera de hacerlo como para que veas un poco lo que son las funciones lambda)

2022-01-10 22:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +        List<Comment> comentariosPorNews = new ArrayList<>();
esta variable ponela en ingles, commentPerNews, newsComments, newsCommentList algo así

2022-01-10 22:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +        for (Comment comment1 : commentService.getAllComments()) {
No está mal, pero podría haberse utilizado una función lambda haciendo uso de stream() y collect() por ejemplo

2022-01-13 21:43 UTC, nicolascareri approved these changes

2022-01-13 21:43 UTC, merged