Ot120 65 agregar paginacion a categorias
alkemyTech/OT120-SERVER pull request #53
Opened 2022-01-14 02:24 UTC by lumalnis

Hola Nico! 
Acá dejo lo de paginación, al final me tuve que guiar con lo que hizo Mauro, no pude lograr hacerlo con lo que me paso el Turco :/ 
![image](https://user-images.githubusercontent.com/83096790/149440867-300347dc-c462-43b6-a6db-08d0ae6fe0ca.png)

2022-01-14 20:57 UTC, nicolascareri requested changes
Esta todo bien fijate los comments

2022-01-14 20:57 UTC, nicolascareri commented on pom.xml
> -  <artifactId>ong</artifactId>
Lu fijate esto esta medio raro

2022-01-14 20:57 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/config/security/SecurityConfig.java
> -                .antMatchers("/auth/**").permitAll()
Esta porque la borraste?

2022-01-14 20:57 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import com.alkemy.ong.model.entity.Category;
y estos imports que no se usan?

2022-01-14 20:57 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import com.alkemy.ong.repository.ICategoryRepository;
borrar

2022-01-14 20:57 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import org.springframework.boot.CommandLineRunner;
borrar

2022-01-14 20:57 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import org.springframework.context.annotation.Bean;
borrar

2022-01-14 20:57 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import java.util.stream.IntStream;
borrar

2022-01-14 21:47 UTC, lumalnis commented on src/main/java/com/alkemy/ong/OngApplication.java
> +import java.util.stream.IntStream;
En esta clase habia inyectado categorias para probar y borre la función pero me olvide de los import.

2022-01-17 02:57 UTC, nicolascareri requested changes

2022-01-17 02:57 UTC, nicolascareri commented on pom.xml
> +       <!--
esto esta bien que este comentado?

2022-01-17 13:49 UTC, lumalnis commented on pom.xml
> +       <!--
Vino asi cuando hice el pull y no quise tocar, creo q esta comentado marcando donde empiezan las dependencias de swagger. Pero ahora consulto en el grupo

2022-01-17 14:02 UTC, nicolascareri requested changes

2022-01-17 14:02 UTC, nicolascareri commented on pom.xml
> +       <!--
si pero aparece como que agregaste vos la depedencia comentada me explico?

2022-01-17 14:27 UTC, nicolascareri requested changes

2022-01-17 14:27 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/config/security/SecurityConfig.java
> +                .antMatchers("/auth/**").permitAll()
esta linea hay que borrarla porque esta en la 58

2022-01-17 14:27 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/config/security/SecurityConfig.java
> +                .antMatchers("/news/{id}/comments").permitAll()
esta tambien

2022-01-17 16:13 UTC, nicolascareri approved these changes

2022-01-17 16:13 UTC, merged