Agrego Endpoint-Creacion-Novedades
alkemyTech/OT120-SERVER pull request #8
Opened 2021-12-18 19:58 UTC by lumalnis

![postman OT120](https://user-images.githubusercontent.com/83096790/146654087-9bd04404-3620-48a4-983f-61d6003c6b81.png)

[https://alkemy-labs.atlassian.net/browse/OT120-36?atlOrigin=eyJpIjoiZDhiOGY2YmU1NWUwNDVjZjliNzhjMmMwYTk0NzQyNWQiLCJwIjoiaiJ9](url)

Nico lo que no me quedo claro es que tengo que hacer acá -> Antes de almacenarla, deberá asignarle la columna type con el valor "news".

2021-12-20 15:16 UTC, nicolascareri approved these changes

2021-12-20 15:16 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    NewsServiceImpl NewServiceImpl;
la variable del newServiceImpl deberia comenzar con minuscula. Dejamos que empiecen con mayuscula las clases nomas

2021-12-20 15:16 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(NewServiceImpl.postNews(news.getName(), news.getContent(), news.getImage(), news.getCategory()));
Yo aca preferiria al postNews pasarle el objeto news entero, asi pasas menos cantidad de parametros y queda mas legible

2021-12-20 15:16 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +    public News postNews(String name, String content, String image, Category category) throws OperationNotAllowedException {
Aca estaria bueno recibir el objeto new entero en vez de 4 parametros

2021-12-20 15:16 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +    INewsRepository INewsRepository;
La variable debe comenzar con minuscula, es camelCase

2021-12-20 15:16 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +            throw new OperationNotAllowedException("El titulo no puede estar vacío");
No deberias usar esta exception porque OperationNotAllowedException devuelve un FORBIDDEN que esta asociado a errores de permisos o authenticacion, cuando queremos reflejar un error de validacion de campos se deberia usar un BAD_REQUEST. Fijate si hay alguna ya creada o si no te podes crear una vos

2021-12-20 15:16 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +public class NewsServiceImpl {
no implementaste la interfaz

2021-12-20 15:17 UTC, nicolascareri requested changes
made changes

2021-12-20 23:58 UTC, lumalnis commented
Buenas! acabo de pushear, espero haber entendido bien y que funcione, deje algunas cosas comentadas para que no se rompa lo de Abel y unas funciones que no tenia actualizadas de Category.
Esta Excepción(FieldInvalidException) está bien o creo una propia ?
**cruzando los dedos...

2021-12-22 03:06 UTC, nicolascareri requested changes

2021-12-22 03:06 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/dto/NewsResponseDto.java
> +   /* public static NewsResponseDto newsToDto(News news) {
Esto si no va a estar se deberia borrar directamente.

2021-12-22 03:06 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +            throw new OperationNotAllowedException("El titulo no puede estar vacío");
Si no otra opcion que tenes es validar directamente en los DTO con la anotacion `@NotBlank` y agregarle el `@Valid al @RequestBody` del controller

2021-12-22 03:06 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
> +        News newsEntity = newsMapper.newsDtoToEntity(newsDto);
Aca deberias setearle la categoria, si l oahces en el mapper descomenta la linea y sino agregasela aca

2021-12-22 18:02 UTC, nicolascareri approved these changes

2021-12-22 18:02 UTC, merged