Ot120 15 endpoint datos publicos
alkemyTech/OT120-SERVER pull request #9
Opened 2021-12-19 22:38 UTC by mtsdlf

![evidence-pr](https://user-images.githubusercontent.com/28317445/146693396-03817aab-bb44-4f78-b7db-e2afe1c431c5.png)

2021-12-19 22:49 UTC, mtsdlf commented
Jira Card
https://alkemy-labs.atlassian.net/browse/OT120-15?atlOrigin=eyJpIjoiODdlMTU3YjdmZDhlNGE4MGEwZDFiYjhjYjE1M2YwZjYiLCJwIjoiaiJ9

2021-12-20 15:20 UTC, nicolascareri requested changes

2021-12-20 15:20 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +  public ResponseEntity<OrganizationDto> getOrganizationById(@Valid @PathVariable Long id) {
El `@Valid` esta de mas

2021-12-20 17:46 UTC, nicolascareri approved these changes

2021-12-20 17:46 UTC, merged